<tr>
<td valign="top">
<p class="bodygrey"><b>Last Name: <font color="#DE7777"><%=rs.Fields("LName").Value %></font><br>
First Name: <font color="#DE7777"><%=rs.Fields("FName").Value %></font></b><br>
<b>AIM SN:</b> <font color="#DE7777"><%=rs.Fields("AIM_SN").Value %></font><br>
<b>Why:</b> <font color="#DE7777"><%=rs.Fields("Why").Value %></font>
</p>
</td>
</tr>
<tr>
<td><hr>
</td></tr>
